<a href="https://colab.research.google.com/github/SettibathulaJyothi/Python-Basics/blob/main/Array_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating an Array using Numpy:**
Different ways to create an array using Numpy are as follows:

Creating one dimensional array:

In [1]:
import numpy
rollno=numpy.array([1,2,3])
print(rollno)

[1 2 3]


Create a sequential 1D array with values as multiples of 10 from 10 to 100:

In [2]:
import numpy as np
a=np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


Creating one-dimensional array with 4 randam values:

In [4]:
import numpy as np
a=np.random.random(4)
print(a)

[0.18452989 0.5188018  0.40775633 0.23393226]


Creating two-dimensional array of  3 rows and 4 columns with random integer values less than 10: