<a href="https://colab.research.google.com/github/SettibathulaJyothi/Python-Basics/blob/main/Mathematical_Operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Using Mathematical Operators on Integer Array**  
Following table shows the use of mathematical operators on integer array:

**Operator Exponential** **


In [ ]:
import numpy as np
marks1=np.array([1,2,3,4,])
marks2=np.array([2,1,2,1])
print(marks1**marks2)
print("marks1 to the power of 3 is :",marks1**3)

[1 2 9 4]
marks1 to the power of 3 is : [ 1  8 27 64]


**Operator Addition +**

In [1]:
import numpy as np
marks1=np.array([7,8,5,4,])
marks2=np.array([5,6,4,7])
print(marks1+marks2)
print("2 marks extra:",marks1+2)

[12 14  9 11]
2 marks extra: [ 9 10  7  6]


**Operator Subtraction -**

In [2]:
import numpy as np
marks1=np.array([7,8,5,4,])
marks2=np.array([5,6,4,7])
print(marks1-marks2)
print("2 marks deducted:",marks1-2)

[ 2  2  1 -3]
2 marks deducted: [5 6 3 2]


**Operator Multiplication***

In [3]:
import numpy as np
marks1=np.array([7,8,5,4,])
marks2=np.array([5,6,4,7])
print(marks1*marks2)
print("2 marks multiplied:",marks1*2)

[35 48 20 28]
2 marks multiplied: [14 16 10  8]
